#define PIKA_SHELL_SAVE_FILE_ENABLE 1
// #define PIKA_DEBUG_ENABLE 1
#define PIKA_SHELL_SAVE_FILE_PATH "/sd/app.py"
#define PIKA_SHELL_SAVE_BYTECODE_ENABLE 1
#define PIKA_SHELL_SAVE_BYTECODE_PATH "/sd/app.py.o"
#define PIKA_SHELL_SAVE_APP_PATH "/sd/app.pika"
#define PIKA_LWIP_ENABLE 1
#define PIKA_STACK_BUFF_SIZE 1024
// 多线程 堆栈大小
#define PIKA_THREAD_STACK_SIZE 1024 * 32
#define PIKA_EVENT_THREAD_STACK_SIZE 1024 * 40
#define PIKA_FREERTOS_ENABLE 1
#define PIKA_OPTIMIZE PIKA_OPTIMIZE_SPEED
#define PIKA_ASSERT_ENABLE 1
#define PIKA_LINUX_COMPATIBLE 1
#define PIKA_READ_FILE_BUFF_SIZE 32 * 1024
