/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___json__H
#define ___json__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__json(Args *args);

char* _json_dumps(PikaObj *self, Arg* d);
Arg* _json_loads(PikaObj *self, char* json_str);

#endif
