/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___modbus_rt__data_trans__H
#define ___modbus_rt__data_trans__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__modbus_rt__data_trans(Args *args);

PikaObj* _modbus_rt__data_trans__bytes2regs(PikaObj *self, Arg* val, int mode);
PikaObj* _modbus_rt__data_trans__double2regs(PikaObj *self, PikaObj* val, int mode);
PikaObj* _modbus_rt__data_trans__float2regs(PikaObj *self, PikaObj* val, int mode);
PikaObj* _modbus_rt__data_trans__int2regs(PikaObj *self, PikaObj* val, int mode);
PikaObj* _modbus_rt__data_trans__long2regs(PikaObj *self, PikaObj* val, int mode);
int _modbus_rt__data_trans__reg2reg(PikaObj *self, int val);
Arg* _modbus_rt__data_trans__regs2bytes(PikaObj *self, PikaObj* val, int mode);
PikaObj* _modbus_rt__data_trans__regs2double(PikaObj *self, PikaObj* val, int mode);
PikaObj* _modbus_rt__data_trans__regs2float(PikaObj *self, PikaObj* val, int mode);
PikaObj* _modbus_rt__data_trans__regs2int(PikaObj *self, PikaObj* val, int mode);
PikaObj* _modbus_rt__data_trans__regs2long(PikaObj *self, PikaObj* val, int mode);
PikaObj* _modbus_rt__data_trans__regs2regs(PikaObj *self, PikaObj* val);
PikaObj* _modbus_rt__data_trans__regs2signed(PikaObj *self, PikaObj* val, int mode);
char* _modbus_rt__data_trans__regs2str(PikaObj *self, PikaObj* val, int mode);
PikaObj* _modbus_rt__data_trans__regs2uint(PikaObj *self, PikaObj* val, int mode);
PikaObj* _modbus_rt__data_trans__str2regs(PikaObj *self, char* val, int mode);
PikaObj* _modbus_rt__data_trans__uint2regs(PikaObj *self, PikaObj* val, int mode);

#endif
