/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __os__H
#define __os__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_os(Args *args);

void os___init__(PikaObj *self);
void os_chdir(PikaObj *self, char* path);
void os_close(PikaObj *self, PikaObj* fd);
Arg* os_fileStat(PikaObj *self);
PikaObj* os_fstat(PikaObj *self, PikaObj* fd);
char* os_getcwd(PikaObj *self);
PikaObj* os_listdir(PikaObj *self, char* path);
int os_lseek(PikaObj *self, PikaObj* fd, int pos, int how);
void os_mkdir(PikaObj *self, char* path, PikaTuple* mode);
PikaObj* os_open(PikaObj *self, char* filename, int flags);
Arg* os_path(PikaObj *self);
char* os_read(PikaObj *self, PikaObj* fd, int len);
void os_remove(PikaObj *self, char* filename);
void os_rename(PikaObj *self, char* old, char* new);
void os_rmdir(PikaObj *self, char* path);
int os_write(PikaObj *self, PikaObj* fd, Arg* buf);

#endif
