/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __os_fileStat__H
#define __os_fileStat__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_os_fileStat(Args *args);

int os_fileStat_st_size(PikaObj *self);

#endif
