
class Aht20:
    def __init__(self): ...

    def readTemp(self) -> float: ...

    def readHumidity(self) -> float: ...

    def startRead(self, callback: any):
        """
        callback 是一个函数， 函数也可以作为变量传递
        """
    def startReadTemp(self, callback: any): ...
    def startReadHumidity(self, callback: any): ...
