/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef ___socket__H
#define ___socket__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New__socket(Args *args);

char* _socket__gethostbyname(PikaObj *self, char* host);
char* _socket__gethostname(PikaObj *self);
Arg* _socket_socket(PikaObj *self);

#endif
