/*
 * [Warning!] This file is auto-generated by pika compiler.
 * Do not edit it manually.
 * The source code is *.pyi file.
 * More details: 
 * English Doc:
 * https://pikadoc-en.readthedocs.io/en/latest/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 * Chinese Doc:
 * http://pikapython.com/doc/PikaScript%20%E6%A8%A1%E5%9D%97%E6%A6%82%E8%BF%B0.html
 */

#ifndef __os_path__H
#define __os_path__H
#include <stdio.h>
#include <stdlib.h>
#include "PikaObj.h"

PikaObj *New_os_path(Args *args);

char* os_path_abspath(PikaObj *self, char* path);
char* os_path_basename(PikaObj *self, char* path);
char* os_path_dirname(PikaObj *self, char* path);
pika_bool os_path_exists(PikaObj *self, char* path);
pika_bool os_path_isabs(PikaObj *self, char* path);
pika_bool os_path_isdir(PikaObj *self, char* path);
pika_bool os_path_isfile(PikaObj *self, char* path);
char* os_path_join(PikaObj *self, PikaTuple* paths);
PikaObj* os_path_split(PikaObj *self, char* path);
PikaObj* os_path_splitext(PikaObj *self, char* path);

#endif
