
import os
from building import *

cwd = GetCurrentDir()
src  = Glob('*.c')
# add cubemx drivers
src = Split('''
Src/stm32f4xx_hal_msp.c
Src/main.c
''')

path = [cwd]
path += [cwd + '/Inc']
path += [cwd + '/Middlewares/ST/STM32_USB_Device_Library/Core/Inc']
path += [cwd + '/Middlewares/ST/STM32_USB_Device_Library/Class/MSC/Inc']

group = DefineGroup('cubemx', src, depend = [''], CPPPATH = path)

objs = [group]

list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
